name: Proyecto_segundaEv
description: "Protecto segunda evaluacion flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.2+1
  sqflite_common_ffi: ^2.0.2+1
  path_provider: ^2.0.11
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imagenes/

